// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Aardvark.FontProvider.DesignTime")>]
[<assembly: AssemblyProductAttribute("Aardvark.FontProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library contains Type-Providers for Aardvark.Rendering.Text Fonts.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Aardvark.FontProvider.DesignTime"
    let [<Literal>] AssemblyProduct = "Aardvark.FontProvider"
    let [<Literal>] AssemblyDescription = "This library contains Type-Providers for Aardvark.Rendering.Text Fonts."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
