// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Aardvark.FontProvider.Runtime")>]
[<assembly: AssemblyProductAttribute("Aardvark.FontProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing FontProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Aardvark.FontProvider.Runtime"
    let [<Literal>] AssemblyProduct = "Aardvark.FontProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing FontProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
